version: '3.8'

services:

  backend:
    build: ./server
    ports:
      - "5000:5000"
    env_file:
      - ./server/.env

  frontend:
    build:
      context: .
      args:
        VITE_API_URL: http://localhost:5000
    ports:
      - "80:80"
    depends_on:
      - backend
